from models import Player

players: dict[int, Player] = {
    1: Player(
        id=1,
        name="Baby Daisy",
        color="Orange",
        batting=4,
        pitching=6,
        fielding=5,
        running=6,
    ),
    2: Player(
        id=2,
        name="Baby DK",
        color="Brown",
        batting=6,
        pitching=3,
        fielding=8,
        running=4,
    ),
    3: Player(
        id=3,
        name="Baby Luigi",
        color="Green",
        batting=2,
        pitching=5,
        fielding=5,
        running=8,
    ),
    4: Player(
        id=4,
        name="Baby Mario",
        color="Red",
        batting=3,
        pitching=5,
        fielding=4,
        running=8,
    ),
    5: Player(
        id=5,
        name="Baby Peach",
        color="Pink",
        batting=2,
        pitching=8,
        fielding=5,
        running=6,
    ),
    6: Player(
        id=6,
        name="Birdo",
        color="Pink",
        batting=8,
        pitching=4,
        fielding=7,
        running=5,
    ),
    7: Player(
        id=7,
        name="Blooper",
        color="White",
        batting=4,
        pitching=6,
        fielding=5,
        running=6,
    ),
    8: Player(
        id=8,
        name="Blue Dry Bones",
        color="Blue",
        batting=7,
        pitching=3,
        fielding=5,
        running=5,
    ),
    9: Player(
        id=9,
        name="Blue Kritter",
        color="Blue",
        batting=6,
        pitching=5,
        fielding=7,
        running=3,
    ),
    10: Player(
        id=10,
        name="Blue Magikoopa",
        color="Blue",
        batting=2,
        pitching=8,
        fielding=8,
        running=2,
    ),
    11: Player(
        id=11,
        name="Blue Noki",
        color="Blue",
        batting=4,
        pitching=5,
        fielding=4,
        running=7,
    ),
    12: Player(
        id=12,
        name="Blue Pianta",
        color="Blue",
        batting=8,
        pitching=5,
        fielding=4,
        running=2,
    ),
    13: Player(
        id=13,
        name="Blue Shy Guy",
        color="Blue",
        batting=4,
        pitching=5,
        fielding=7,
        running=4,
    ),
    14: Player(
        id=14,
        name="Blue Toad",
        color="Blue",
        batting=6,
        pitching=4,
        fielding=3,
        running=7,
    ),
    15: Player(
        id=15,
        name="Blue Yoshi",
        color="Blue",
        batting=2,
        pitching=4,
        fielding=6,
        running=8,
    ),
    16: Player(
        id=16,
        name="Boo",
        color="White",
        batting=3,
        pitching=9,
        fielding=3,
        running=5,
    ),
    17: Player(
        id=17,
        name="Boomerang Bro",
        color="Blue",
        batting=7,
        pitching=5,
        fielding=5,
        running=3,
    ),
    18: Player(
        id=18,
        name="Bowser",
        color="Black",
        batting=10,
        pitching=5,
        fielding=3,
        running=3,
    ),
    19: Player(
        id=19,
        name="Bowser Jr.",
        color="Black",
        batting=7,
        pitching=5,
        fielding=4,
        running=7,
    ),
    20: Player(
        id=20,
        name="Brown Kritter",
        color="Brown",
        batting=7,
        pitching=3,
        fielding=7,
        running=4,
    ),
    21: Player(
        id=21,
        name="Daisy",
        color="Orange",
        batting=6,
        pitching=7,
        fielding=8,
        running=5,
    ),
    22: Player(
        id=22,
        name="Dark Bones",
        color="Red",
        batting=7,
        pitching=5,
        fielding=4,
        running=5,
    ),
    23: Player(
        id=23,
        name="Diddy Kong",
        color="None",
        batting=4,
        pitching=5,
        fielding=8,
        running=6,
    ),
    24: Player(
        id=24,
        name="Dixie Kong",
        color="Pink",
        batting=3,
        pitching=3,
        fielding=8,
        running=7,
    ),
    25: Player(
        id=25,
        name="Donkey Kong",
        color="Brown",
        batting=9,
        pitching=6,
        fielding=3,
        running=2,
    ),
    26: Player(
        id=26,
        name="Dry Bones",
        color="White",
        batting=7,
        pitching=4,
        fielding=4,
        running=5,
    ),
    27: Player(
        id=27,
        name="Fire Bro",
        color="Red",
        batting=8,
        pitching=3,
        fielding=6,
        running=3,
    ),
    28: Player(
        id=28,
        name="Funky Kong",
        color="Light Blue",
        batting=8,
        pitching=4,
        fielding=6,
        running=3,
    ),
    29: Player(
        id=29,
        name="Goomba",
        color="Brown",
        batting=3,
        pitching=6,
        fielding=6,
        running=4,
    ),
    30: Player(
        id=30,
        name="Gray Shy Guy",
        color="Black",
        batting=4,
        pitching=4,
        fielding=8,
        running=4,
    ),
    31: Player(
        id=31,
        name="Green Dry Bones",
        color="Green",
        batting=7,
        pitching=3,
        fielding=4,
        running=6,
    ),
    32: Player(
        id=32,
        name="Green Kritter",
        color="Green",
        batting=7,
        pitching=4,
        fielding=7,
        running=3,
    ),
    33: Player(
        id=33,
        name="Green Magikoopa",
        color="Green",
        batting=2,
        pitching=7,
        fielding=8,
        running=2,
    ),
    34: Player(
        id=34,
        name="Green Noki",
        color="Green",
        batting=5,
        pitching=4,
        fielding=4,
        running=7,
    ),
    35: Player(
        id=35,
        name="Green Paratroopa",
        color="Green",
        batting=5,
        pitching=3,
        fielding=7,
        running=5,
    ),
    36: Player(
        id=36,
        name="Green Shy Guy",
        color="Green",
        batting=5,
        pitching=3,
        fielding=7,
        running=5,
    ),
    37: Player(
        id=37,
        name="Green Toad",
        color="Green",
        batting=5,
        pitching=4,
        fielding=4,
        running=7,
    ),
    38: Player(
        id=38,
        name="Hammer Bro",
        color="Green",
        batting=7,
        pitching=4,
        fielding=6,
        running=3,
    ),
    39: Player(
        id=39,
        name="King Boo",
        color="White",
        batting=7,
        pitching=7,
        fielding=3,
        running=4,
    ),
    40: Player(
        id=40,
        name="King K. Rool",
        color="Green",
        batting=10,
        pitching=6,
        fielding=2,
        running=1,
    ),
    41: Player(
        id=41,
        name="Koopa",
        color="Green",
        batting=6,
        pitching=3,
        fielding=4,
        running=6,
    ),
    42: Player(
        id=42,
        name="Light Blue Yoshi",
        color="Light Blue",
        batting=3,
        pitching=3,
        fielding=6,
        running=8,
    ),
    43: Player(
        id=43,
        name="Luigi",
        color="Green",
        batting=6,
        pitching=6,
        fielding=7,
        running=7,
    ),
    44: Player(
        id=44,
        name="Mario",
        color="Red",
        batting=7,
        pitching=6,
        fielding=6,
        running=7,
    ),
    45: Player(
        id=45,
        name="Mii",
        color="None",
        batting=6,
        pitching=6,
        fielding=6,
        running=6,
    ),
    46: Player(
        id=46,
        name="Monty Mole",
        color="Brown",
        batting=4,
        pitching=4,
        fielding=5,
        running=7,
    ),
    47: Player(
        id=47,
        name="Paragoomba",
        color="Brown",
        batting=3,
        pitching=6,
        fielding=7,
        running=5,
    ),
    48: Player(
        id=48,
        name="Paratroopa",
        color="Red",
        batting=4,
        pitching=4,
        fielding=7,
        running=5,
    ),
    49: Player(
        id=49,
        name="Peach",
        color="Pink",
        batting=4,
        pitching=9,
        fielding=8,
        running=5,
    ),
    50: Player(
        id=50,
        name="Petey Piranha",
        color="Light Green",
        batting=10,
        pitching=4,
        fielding=5,
        running=2,
    ),
    51: Player(
        id=51,
        name="Pink Yoshi",
        color="Pink",
        batting=3,
        pitching=2,
        fielding=6,
        running=9,
    ),
    52: Player(
        id=52,
        name="Purple Toad",
        color="Purple",
        batting=6,
        pitching=5,
        fielding=2,
        running=7,
    ),
    53: Player(
        id=53,
        name="Red Koopa",
        color="Red",
        batting=6,
        pitching=4,
        fielding=3,
        running=6,
    ),
    54: Player(
        id=54,
        name="Red Kritter",
        color="Red",
        batting=8,
        pitching=3,
        fielding=7,
        running=3,
    ),
    55: Player(
        id=55,
        name="Red Magikoopa",
        color="Red",
        batting=3,
        pitching=8,
        fielding=8,
        running=1,
    ),
    56: Player(
        id=56,
        name="Red Noki",
        color="Red",
        batting=4,
        pitching=4,
        fielding=5,
        running=7,
    ),
    57: Player(
        id=57,
        name="Red Pianta",
        color="Red",
        batting=8,
        pitching=4,
        fielding=4,
        running=2,
    ),
    58: Player(
        id=58,
        name="Red Shy Guy",
        color="Red",
        batting=5,
        pitching=4,
        fielding=7,
        running=4,
    ),
    59: Player(
        id=59,
        name="Red Toad",
        color="Red",
        batting=5,
        pitching=5,
        fielding=3,
        running=7,
    ),
    60: Player(
        id=60,
        name="Red Yoshi",
        color="Red",
        batting=4,
        pitching=3,
        fielding=4,
        running=8,
    ),
    61: Player(
        id=61,
        name="Tiny Kong",
        color="Light Blue",
        batting=5,
        pitching=5,
        fielding=7,
        running=5,
    ),
    62: Player(
        id=62,
        name="Toadette",
        color="Pink",
        batting=3,
        pitching=5,
        fielding=4,
        running=8,
    ),
    63: Player(
        id=63,
        name="Toadsworth",
        color="Brown",
        batting=3,
        pitching=7,
        fielding=7,
        running=3,
    ),
    64: Player(
        id=64,
        name="Waluigi",
        color="Purple",
        batting=4,
        pitching=8,
        fielding=8,
        running=5,
    ),
    65: Player(
        id=65,
        name="Wario",
        color="Yellow",
        batting=8,
        pitching=5,
        fielding=3,
        running=4,
    ),
    66: Player(
        id=66,
        name="Wiggler",
        color="Yellow",
        batting=7,
        pitching=3,
        fielding=4,
        running=7,
    ),
    67: Player(
        id=67,
        name="Yellow Magikoopa",
        color="Yellow",
        batting=3,
        pitching=7,
        fielding=8,
        running=2,
    ),
    68: Player(
        id=68,
        name="Yellow Pianta",
        color="Yellow",
        batting=8,
        pitching=4,
        fielding=4,
        running=2,
    ),
    69: Player(
        id=69,
        name="Yellow Shy Guy",
        color="Yellow",
        batting=4,
        pitching=4,
        fielding=7,
        running=5,
    ),
    70: Player(
        id=70,
        name="Yellow Toad",
        color="Yellow",
        batting=6,
        pitching=3,
        fielding=4,
        running=7,
    ),
    71: Player(
        id=71,
        name="Yellow Yoshi",
        color="Yellow",
        batting=4,
        pitching=3,
        fielding=6,
        running=7,
    ),
    72: Player(
        id=72,
        name="Yoshi",
        color="Light Green",
        batting=4,
        pitching=4,
        fielding=6,
        running=9,
    ),
}